"""empty message

Revision ID: 865d4d5fe22f
Revises: 5d2daf49c8d3
Create Date: 2020-01-23 09:50:29.569070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865d4d5fe22f'
down_revision = '5d2daf49c8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_genres_artist_id_fkey', 'artist_genres', type_='foreignkey')
    op.create_foreign_key(None, 'artist_genres', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artist_genres', type_='foreignkey')
    op.create_foreign_key('artist_genres_artist_id_fkey', 'artist_genres', 'Venue', ['artist_id'], ['id'])
    # ### end Alembic commands ###
